### ISSUE TITLE
Property `disableTls` does not exist

### ISSUE THREAD

**Issue by khal3d** [isaaceindhoven/composer-velocita#3]
Hello,

I'm trying to enable the Velocita plugin on Composer v2.0.9, but I keep getting the following error whenever I try to run any composer command

```bash
root@a406eae2ba29:/var/www/html# composer update
              
  [RuntimeException]                        
  Property `disableTls` could not be found  
                                      
  [ReflectionException]               
  Property disableTls does not exist  
```

Please advise

**Comment by gmta** [comment]
Hi @khal3d, the internal structure of a certain class in Composer 2.0.0 was changed between the release candidates and the final stable release of Composer 2, resulting in this error. This needs to be fixed.

**Comment by gmta** [comment]
The property was removed [here](https://github.com/composer/composer/compare/2.0.0-RC1...2.0.0-RC2#diff-c04a3c196fdb87800809f28ad5819fbc90adce88a32aced6072a1bba65788062L43).

**Comment by khal3d** [comment]
Hi, @GMTA Thank you so much for your fast reply.

So, do you think if we used `$this->compatibilityDetector->getComposer()->getConfig()->get('disable-tls')` instead of ` $this->getAccessibleProperty($oldRfs, 'disableTls');` will solve this issue?

**Comment by gmta** [comment]
@khal3d Unfortunately not, since there are a lot of factors that come into play when deciding the final value for `$disableTls`, so the right route in my opinion is to extract the effective value through reflection.

I'm working on a fix - nearly done!

**Comment by gmta** [comment]
@khal3d Could you please try version `3.1.0` and let me know if that works for you as well?

https://packagist.org/packages/isaac/composer-velocita#3.1.0

**Comment by khal3d** [comment]
Perfectly working. Thank you so much @GMTA 👍

We can close this issue now.
